version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:

  Test-Backend:

    steps:
      - node/install
      - checkout
      - run:
          name: Install
          command: |
            npm run backend:install
      - run:
          name: Build
          command: |
            npm run backend:build
      - run:
          name: Unit Test
          command: |
            npm run backend:test:unit

workflows:
  version: 2
  workflow:
    jobs:

      - Test-Backend:
          filters:
            branches:
              only:
                - master
