branch-defaults:
  default:
    environment: minaroid-store
environment-defaults:
  minaroid-store:
    branch: null
    repository: null

global:
  application_name: minaroid-store
  default_ec2_keyname: minaroid-store
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
